export const SPECIAL_FORM_ITEMS: Record<string, string> = {
  // Mega Evolutions
  'Mega Venusaur': 'venusaurite',
  'Mega Charizard X': 'charizardite-x',
  'Mega Charizard Y': 'charizardite-y',
  'Mega Blastoise': 'blastoisinite',
  'Mega Beedrill': 'beedrillite',
  'Mega Pidgeot': 'pidgeotite',
  'Mega Alakazam': 'alakazite',
  'Mega Slowbro': 'slowbronite',
  'Mega Gengar': 'gengarite',
  'Mega Kangaskhan': 'kangaskhanite',
  'Mega Pinsir': 'pinsirite',
  'Mega Gyarados': 'gyaradosite',
  'Mega Aerodactyl': 'aerodactylite',
  'Mega Mewtwo X': 'mewtwonite-x',
  'Mega Mewtwo Y': 'mewtwonite-y',
  'Mega Ampharos': 'ampharosite',
  'Mega Steelix': 'steelixite',
  'Mega Scizor': 'scizorite',
  'Mega Heracross': 'heracronite',
  'Mega Houndoom': 'houndoominite',
  'Mega Tyranitar': 'tyranitarite',
  'Mega Sceptile': 'sceptilite',
  'Mega Blaziken': 'blazikenite',
  'Mega Swampert': 'swampertite',
  'Mega Gardevoir': 'gardevoirite',
  'Mega Sableye': 'sablenite',
  'Mega Mawile': 'mawilite',
  'Mega Aggron': 'aggronite',
  'Mega Medicham': 'medichamite',
  'Mega Manectric': 'manectite',
  'Mega Sharpedo': 'sharpedonite',
  'Mega Camerupt': 'cameruptite',
  'Mega Altaria': 'altarianite',
  'Mega Banette': 'banettite',
  'Mega Absol': 'absolite',
  'Mega Glalie': 'glalitite',
  'Mega Salamence': 'salamencite',
  'Mega Metagross': 'metagrossite',
  'Mega Latias': 'latiasite',
  'Mega Latios': 'latiosite',
  'Mega Lopunny': 'lopunnite',
  'Mega Garchomp': 'garchompite',
  'Mega Lucario': 'lucarionite',
  'Mega Abomasnow': 'abomasite',
  'Mega Gallade': 'galladite',
  'Mega Audino': 'audinite',
  'Mega Diancie': 'diancite',
  // Primal Reversions
  'Groudon Primal': 'red-orb',
  'Kyogre Primal': 'blue-orb',
  // Ultra Necrozma (Ultra form)
  'Necrozma Ultra': 'ultranecrozium-z--held',
  'Dialga Origin': 'adamant-crystal',
  'Palkia Origin': 'lustrous-orb',
  'Giratina Origin': 'griseous-orb',
};
